# Generated by Django 3.1.5 on 2021-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandId', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
    ]
