# Generated by Django 3.1.2 on 2021-02-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomersOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField()),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('MobiileNo', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactPersonNo', models.CharField(max_length=100)),
                ('AdharNo', models.CharField(max_length=100)),
                ('JoiningDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ItemCode', models.CharField(max_length=100)),
                ('PrintName', models.CharField(max_length=100)),
                ('PurchasePrice', models.CharField(max_length=100)),
                ('SalePrice', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('LowLevelLimit', models.CharField(max_length=100)),
                ('Discount', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=10)),
                ('StockQTY', models.CharField(max_length=10)),
                ('CreatedAt', models.DateField()),
                ('ProductImage', models.CharField(max_length=100)),
                ('BrandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.brand')),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Contact', models.CharField(max_length=20)),
                ('BillingName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('PaymentStatus', models.CharField(max_length=100)),
                ('OrderStatus', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=100)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.customersonline')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('PANNo', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactPersonNo', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOnlineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('SalesOrderOnlineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.salesorderonline')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('UserId', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('EmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.employee')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.role')),
            ],
        ),
    ]
