# Generated by Django 2.1.5 on 2021-03-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('AdminUserid', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('UserId', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandId', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('CompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=20)),
                ('PanNo', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=20)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('EmailId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersOnline',
            fields=[
                ('CustomersOnlineId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('MobileNo', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactPersonNo', models.CharField(max_length=100)),
                ('AdhaarNo', models.CharField(max_length=100)),
                ('JoiningDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ExpenseId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('ExpenseType', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('PaidTo', models.CharField(max_length=100)),
                ('PaidBy', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ItemCode', models.CharField(max_length=100)),
                ('PrintName', models.CharField(max_length=100)),
                ('PurchasePrice', models.CharField(max_length=100)),
                ('SalePrice', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('LowLevelLimit', models.IntegerField()),
                ('Discount', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=10)),
                ('StockQTY', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ProductImage', models.CharField(max_length=100)),
                ('Brand', models.ForeignKey(db_column='BrandId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Brand')),
                ('Category', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('PurchaseBillId', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('BillNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PurchaseType', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('SubTotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Product')),
                ('PurchaseBillDetailId', models.ForeignKey(db_column='PurchaseBillId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.PurchaseBill')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('BillNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PurchaseType', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('SubTotal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=100)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Product')),
                ('PurchaseOrderDetailId', models.ForeignKey(db_column='PurchaseOrderId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOfflineDetail',
            fields=[
                ('SalesOrderOfflineDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.CharField(max_length=10)),
                ('GST', models.CharField(default=0, max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='InventoryApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOnline',
            fields=[
                ('SalesOrderOnlineId', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Contact', models.CharField(max_length=20)),
                ('BillingName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('PaymentStatus', models.CharField(max_length=100)),
                ('OrderStatus', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=100)),
                ('CustomerId', models.ForeignKey(db_column='CustomersOnlineId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.CustomersOnline')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOnlineDetail',
            fields=[
                ('SalesOrderOnlineDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Product')),
                ('SalesOrderOnlineId', models.ForeignKey(db_column='SalesOrderOnlineId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.SalesOrderOnline')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrdersOffline',
            fields=[
                ('SalesOrderOfflineId', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('CustomerName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('PaymentMode', models.CharField(max_length=100)),
                ('SubTotal', models.CharField(default=0, max_length=100)),
                ('GST', models.CharField(default=0, max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('Balance', models.CharField(default=0, max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustments',
            fields=[
                ('StockAdjustmentsId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=10)),
                ('Reason', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Remarks', models.CharField(max_length=200)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('PANNo', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('ContactPerson', models.CharField(default='ABC', max_length=100)),
                ('ContactPersonNo', models.CharField(default='1234567890', max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesorderofflinedetail',
            name='SalesOrdersOfflineId',
            field=models.ForeignKey(db_column='SalesOrderOfflineId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.SalesOrdersOffline'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Supplier',
            field=models.ForeignKey(db_column='SupplierId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Supplier'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='Supplier',
            field=models.ForeignKey(db_column='SupplierId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Supplier'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='EmployeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Employee'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='Role',
            field=models.ForeignKey(db_column='RoleId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.Role'),
        ),
    ]
