# Generated by Django 3.1.6 on 2021-02-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandId', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
    ]
