# Generated by Django 3.1.6 on 2021-03-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PurchaseOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('BillNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PurchaseType', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('SubTotal', models.CharField(max_length=100)),
                ('Supplier', models.ForeignKey(db_column='SupplierId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=100)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('PurchaseOrderDetailId', models.ForeignKey(db_column='PurchaseOrderId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.purchaseorder')),
            ],
        ),
    ]
