# Generated by Django 3.1.2 on 2021-02-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderofflinedetail',
            old_name='Quntity',
            new_name='Quantity',
        ),
    ]
