# Generated by Django 3.1.2 on 2021-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='LowLevelLimit',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='StockQTY',
            field=models.IntegerField(max_length=10),
        ),
    ]
