# Generated by Django 3.1.6 on 2021-02-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='Status',
        ),
    ]
