# Generated by Django 3.1.2 on 2021-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20210212_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesordersoffline',
            name='Date',
            field=models.DateField(),
        ),
    ]
