# Generated by Django 3.1.2 on 2021-02-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20210220_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderofflinedetail',
            old_name='UnitPrice',
            new_name='SalePrice',
        ),
    ]
