# Generated by Django 3.1.2 on 2021-02-11 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20210211_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
