# Generated by Django 3.1.2 on 2021-03-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20210304_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustments',
            fields=[
                ('StockAdjustmentsId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=10)),
                ('Reason', models.CharField(max_length=30)),
                ('Quantiy', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Remarks', models.CharField(max_length=200)),
                ('Product', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
            ],
        ),
    ]
