# Generated by Django 3.1.6 on 2021-03-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_purchaseorder_purchaseorderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnDetail',
            fields=[
                ('PurchaseReturnDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('GST', models.CharField(max_length=100)),
                ('ProductId', models.ForeignKey(db_column='ProductId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('PurchaseReturnId', models.AutoField(primary_key=True, serialize=False)),
                ('ReturnBillNo', models.CharField(max_length=100)),
                ('PurchaseBillNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('ReturnType', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=100)),
                ('SubTotal', models.CharField(max_length=100)),
                ('Supplier', models.ForeignKey(db_column='SupplierId', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.supplier')),
            ],
        ),
    ]
