# Generated by Django 3.1.2 on 2021-03-04 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_stockadjustments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockadjustments',
            old_name='Quantiy',
            new_name='Quantity',
        ),
    ]
