# Generated by Django 3.1.2 on 2021-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_auto_20210211_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
