# Generated by Django 3.1.2 on 2021-02-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_auto_20210212_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='ContactPerson',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='ContactPersonNo',
        ),
    ]
