# Generated by Django 3.1.2 on 2021-02-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_auto_20210211_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('PurchaseType', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('PaymentMode', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.adminuser')),
                ('SupplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrdersOffline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('CustomerName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('PaymentMode', models.CharField(max_length=100)),
                ('TotalAmount', models.CharField(max_length=10)),
                ('AmountPaid', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderOfflineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('SalesOrdersOfflineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.salesordersoffline')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=10)),
                ('SalePrice', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10)),
                ('Discount', models.CharField(max_length=10)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.product')),
                ('PurchaseBillDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.purchasebill')),
            ],
        ),
    ]
