# Generated by Django 3.1.2 on 2021-02-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='panNo',
            new_name='PanNo',
        ),
    ]
