# Generated by Django 3.1.6 on 2021-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_auto_20210213_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('OwnerName', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=20)),
                ('panNo', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=20)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('EmailId', models.CharField(max_length=50)),
            ],
        ),
    ]
