# Generated by Django 3.1.6 on 2021-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='id',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='CompanyId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
